import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import { Store } from '../src/db.mjs';import { DwsService } from '../src/service.mjs';import { nowIso } from '../src/utils.mjs';
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'dws-node-')),db=path.join(dir,'test.sqlite'),store=new Store(db);store.seed({bootstrapAdminEmail:'admin@test.local',bootstrapAdminName:'Admin'});const now=nowIso();store.insert('Contractors',{ContractorID:'C1',ContractorName:'Alpha',Active:true,CreatedAt:now,UpdatedAt:now});store.insert('Contractors',{ContractorID:'C2',ContractorName:'Beta',Active:true,CreatedAt:now,UpdatedAt:now});store.insert('Crews',{CrewID:'CR1',CrewName:'Alpha Crew',ContractorID:'C1',Parish:'Kingston',Active:true,CreatedAt:now,UpdatedAt:now});store.insert('Crews',{CrewID:'CR2',CrewName:'Beta Crew',ContractorID:'C2',Parish:'Kingston',Active:true,CreatedAt:now,UpdatedAt:now});store.insert('CrewMembers',{CrewMemberID:'M1',CrewID:'CR1',EmployeeName:'Alice Brown',Active:true,CreatedAt:now,UpdatedAt:now});store.insert('CrewMembers',{CrewMemberID:'M2',CrewID:'CR1',EmployeeName:'Bob Green',Active:true,CreatedAt:now,UpdatedAt:now});store.insert('CrewMembers',{CrewMemberID:'M3',CrewID:'CR2',EmployeeName:'Dawn Black',Active:true,CreatedAt:now,UpdatedAt:now});store.insert('Users',{UserID:'U-C1',Email:'contractor@test.local',Name:'Contractor',Role:'Contractor',ContractorID:'C1',AuthorizedParishes:'Kingston',Active:true,CreatedAt:now,UpdatedAt:now});const service=new DwsService(store,{databasePath:db});return{dir,db,store,service,admin:service.getUserByEmail('admin@test.local'),contractor:service.getUserByEmail('contractor@test.local')};}
function jobs(ids){return ids.map((id,i)=>({JobID:id,ProblemReported:'Fault',AssignedTime:`08:${String(i*5).padStart(2,'0')}`,OnSiteTime:`08:${String(20+i*5).padStart(2,'0')}`,CompletedTime:`09:${String(i*5).padStart(2,'0')}`,ActionTaken:'Repair',Remarks:'Done'}));}
function cleanup(x){x.store.close();fs.rmSync(x.dir,{recursive:true,force:true});}

test('contractor session and template are scoped to contractor crews/members',()=>{const x=fixture();try{const s=x.service.getSessionData(x.contractor);assert.deepEqual(s.contractors.map(c=>c.ContractorID),['C1']);assert.deepEqual(s.crews.map(c=>c.CrewID),['CR1']);assert.deepEqual(s.crewMembers.map(m=>m.CrewID),['CR1','CR1']);const t=x.service.getTemplateData(x.contractor,'C2');assert.equal(t.templateMeta.GeneratedForContractorID,'C1');assert.deepEqual(t.crews.map(r=>r[1]),['CR1']);assert.equal(t.crewMembers[0][2],'Alice Brown, Bob Green');}finally{cleanup(x);}});

test('admin can generate contractor-bound template',()=>{const x=fixture();try{const t=x.service.getTemplateData(x.admin,'C2');assert.deepEqual(t.contractors.map(r=>r[1]),['C2']);assert.deepEqual(t.crews.map(r=>r[1]),['CR2']);assert.equal(t.crewMembers[0][2],'Dawn Black');}finally{cleanup(x);}});

test('manual worksheet calculates six-job compliance',()=>{const x=fixture();try{const r=x.service.saveWorksheet(x.contractor,{ContractorID:'C1',WorkTypeID:'WTP-02',DateWorked:'2026-09-20',Parish:'Kingston',Location:'Kgn',CrewID:'CR1',TeamMembers:'Alice Brown, Bob Green',ShiftID:'SHF-01',jobs:jobs(['J1','J2','J3','J4','J5','J6'])});assert.equal(r.summary.jobsCompleted,6);assert.equal(r.summary.productionCompliance,100);assert.equal(r.worksheet.ContractorID,'C1');}finally{cleanup(x);}});

test('duplicate job id does not increase completed-job count',()=>{const x=fixture();try{const r=x.service.saveWorksheet(x.contractor,{ContractorID:'C1',WorkTypeID:'WTP-02',DateWorked:'2026-09-21',Parish:'Kingston',CrewID:'CR1',TeamMembers:'Alice Brown',ShiftID:'SHF-01',jobs:jobs(['A','B','C','D','E','E'])});assert.equal(r.summary.jobsCompleted,5);assert.equal(r.summary.duplicateJobs,1);assert.ok(r.exceptions.some(e=>e.ExceptionType==='DUPLICATE_JOB_ID'));}finally{cleanup(x);}});

test('two bulk imports matching logical identity merge into one worksheet',()=>{const x=fixture();try{const meta={TemplateName:'Daily Work Sheet Logging Bulk Import Template',TemplateVersion:'1.1',GeneratedForContractorID:'C1',GeneratedForContractorName:'Alpha'};const mk=ids=>ids.map((id,i)=>({'Contractor':'Alpha','Work Type':'Outage Response','Date Worked':'2026-09-22','Parish':'Kingston','Location':'Kgn','Crew':'Alpha Crew','Team Members':'Alice Brown, Bob Green','Shift':'7 AM - 3 PM','Job ID':id,'Problem Reported':'Fault','Assigned Time':`08:${String(i*5).padStart(2,'0')}`,'On-site Time':`08:${String(20+i*5).padStart(2,'0')}`,'Completed Time':`09:${String(i*5).padStart(2,'0')}`,'Action Taken':'Repair','Remarks':'Done'}));const a=x.service.importBulkRows(x.contractor,mk(['J1','J2','J3']),meta),b=x.service.importBulkRows(x.contractor,mk(['J4','J5','J6']),meta);assert.equal(a.created,1);assert.equal(b.merged,1);assert.equal(x.store.count('Worksheets'),1);const ws=x.store.all('Worksheets')[0];assert.equal(Number(ws.JobsCompleted),6);assert.equal(x.store.filter('WorksheetJobs','WorksheetID',ws.WorksheetID).length,6);}finally{cleanup(x);}});

test('contractor-bound import rejects wrong crew member',()=>{const x=fixture();try{const meta={TemplateName:'Daily Work Sheet Logging Bulk Import Template',TemplateVersion:'1.1',GeneratedForContractorID:'C1',GeneratedForContractorName:'Alpha'};const rows=[{'Contractor':'Alpha','Work Type':'Outage Response','Date Worked':'2026-09-23','Parish':'Kingston','Crew':'Alpha Crew','Team Members':'Dawn Black','Shift':'7 AM - 3 PM','Job ID':'X1'}];const r=x.service.importBulkRows(x.contractor,rows,meta);assert.equal(r.failed,1);assert.match(r.errors[0].message,/not assigned/i);}finally{cleanup(x);}});
