import {
  APP_VERSION, BULK_TEMPLATE, SCHEMA, ADMIN_ENTITIES, LEGAL_CONTENT_VERSION
} from './schema.mjs';
import {
  newId, nowIso, cleanString, normalizeEmail, displayNameFromEmail, truthy, num, round2, sum,
  averageNumeric, cleanTime, normalizeImportedTime, parseFlexibleTime, normalizeDateString, validateDate,
  hasAnyJobData, normalizeHeader, stringifySafe, formatMinutesText, normalizeIdentityText,
  mergeDelimitedValues, sortByOrder, findByIdOrName, extractSpreadsheetId, sanitizeAdminValue
} from './utils.mjs';
import { evaluateJob, calculateDurations, complianceStatus, normalizeWeights, makeException } from './compliance.mjs';

const HEADER_ALIASES = Object.freeze({
  contractor:'Contractor',worktype:'WorkType',dateworked:'DateWorked',parish:'Parish',location:'Location',crew:'Crew',team:'TeamMembers',teammembers:'TeamMembers',shift:'Shift',jobid:'JobID',customername:'CustomerName',customersname:'CustomerName',customeraddress:'CustomerAddress',customersaddress:'CustomerAddress',problemreported:'ProblemReported',assigned:'AssignedTime',assignedtime:'AssignedTime',onsite:'OnSiteTime',onsitetime:'OnSiteTime',completed:'CompletedTime',completedtime:'CompletedTime',actiontaken:'ActionTaken',materialused:'MaterialUsed',voltagefound:'VoltageFound',voltageleft:'VoltageLeft',remarks:'Remarks'
});

export class DwsService {
  constructor(store, { databasePath = store.dbPath } = {}) { this.store=store; this.databasePath=databasePath; }

  getUserByEmail(email) {
    const target=normalizeEmail(email);
    const user=this.store.all('Users').find(u=>normalizeEmail(u.Email)===target && truthy(u.Active));
    if(!user) throw new Error('Access denied. Your account is not an active user of this application.');
    return user;
  }
  authorize(user, roles) {
    if(!user) throw new Error('Authentication required.');
    if(roles?.length && !roles.includes(String(user.Role))) throw new Error('Access denied. Your role does not permit this action.');
    return user;
  }
  sanitizeUser(user){return{UserID:user.UserID,Email:user.Email,Name:user.Name,Role:user.Role,ContractorID:user.ContractorID,AuthorizedParishes:user.AuthorizedParishes||''};}
  settings(){const map={};for(const r of this.store.all('Settings'))map[String(r.Key)]=r.Value;return map;}
  active(table){return this.store.all(table).filter(x=>truthy(x.Active));}
  allowedParishes(user){return cleanString(user.AuthorizedParishes).split(',').map(x=>x.trim()).filter(Boolean);}
  enforceParish(user, parish){const allowed=this.allowedParishes(user);if(!allowed.length)return;const set=new Set(allowed.map(x=>x.toLowerCase()));if(!set.has(cleanString(parish).toLowerCase()))throw new Error(`You are not authorized to submit worksheets for ${parish}.`);}

  getSessionData(user){
    this.authorize(user,['Admin','Superuser','Contractor']); const settings=this.settings();
    const data={user:this.sanitizeUser(user),settings,contractors:this.active('Contractors'),crews:this.active('Crews'),crewMembers:this.active('CrewMembers'),parishes:this.active('Parishes').sort(sortByOrder('SortOrder','ParishName')),shifts:this.active('Shifts').sort(sortByOrder('SortOrder','ShiftName')),workTypes:this.active('WorkTypes').sort(sortByOrder('SortOrder','WorkTypeName')),legal:this.store.all('LegalContent'),appVersion:APP_VERSION};
    if(String(user.Role)==='Contractor'){
      data.contractors=data.contractors.filter(x=>String(x.ContractorID)===String(user.ContractorID));
      data.crews=data.crews.filter(x=>String(x.ContractorID)===String(user.ContractorID));
      const ids=new Set(data.crews.map(x=>String(x.CrewID)));data.crewMembers=data.crewMembers.filter(x=>ids.has(String(x.CrewID)));
    }
    const allowed=this.allowedParishes(user);if(allowed.length){const set=new Set(allowed.map(x=>x.toLowerCase()));data.parishes=data.parishes.filter(x=>set.has(cleanString(x.ParishName).toLowerCase()));data.crews=data.crews.filter(x=>!x.Parish||set.has(cleanString(x.Parish).toLowerCase()));const ids=new Set(data.crews.map(x=>String(x.CrewID)));data.crewMembers=data.crewMembers.filter(x=>ids.has(String(x.CrewID)));}
    return data;
  }

  getWorksheet(user,worksheetId){this.authorize(user,['Admin','Superuser','Contractor']);const ws=this.restrictWorksheets(this.store.all('Worksheets'),user).find(w=>String(w.WorksheetID)===String(worksheetId));if(!ws)throw new Error('Worksheet not found or access denied.');const jobs=this.store.filter('WorksheetJobs','WorksheetID',worksheetId).sort((a,b)=>num(a.JobSequence)-num(b.JobSequence));return{worksheet:ws,jobs};}
  saveWorksheet(user,payload){this.authorize(user,['Admin','Superuser','Contractor']);return this.store.transaction(()=>this.persistWorksheet(payload||{},user,payload?.WorksheetID?'Manual Edit':'Manual Entry'));}
  deleteWorksheet(user,worksheetId){this.authorize(user,['Admin']);return this.store.transaction(()=>{const old=this.store.findOne('Worksheets','WorksheetID',worksheetId);if(!old)throw new Error('Worksheet not found.');this.store.deleteWhere('WorksheetJobs','WorksheetID',worksheetId);this.store.deleteWhere('Exceptions','WorksheetID',worksheetId);this.store.deleteWhere('Worksheets','WorksheetID',worksheetId);this.audit(user,'DELETE','Worksheet',worksheetId,'Deleted worksheet and related job/exception records.',old,'');return{worksheetId};});}

  existingJobKeysForDate(dateWorked,excludeWorksheetId){const ids=new Set(this.store.all('Worksheets').filter(w=>String(w.DateWorked)===String(dateWorked)&&String(w.WorksheetID)!==String(excludeWorksheetId||'')).map(w=>String(w.WorksheetID)));return new Set(this.store.all('WorksheetJobs').filter(j=>ids.has(String(j.WorksheetID))&&j.JobID).map(j=>`${dateWorked}|${cleanString(j.JobID).toUpperCase()}`));}

  validateTeamMembersForCrew(crewId, teamMembers, {strict=false}={}) {
    if(!strict || !cleanString(teamMembers)) return;
    const allowed=new Set(this.active('CrewMembers').filter(m=>String(m.CrewID)===String(crewId)).map(m=>cleanString(m.EmployeeName).replace(/\s+/g,' ').toUpperCase()).filter(Boolean));
    const supplied=cleanString(teamMembers).split(/[;,\n]+/).map(cleanString).filter(Boolean);const invalid=supplied.filter(x=>!allowed.has(x.replace(/\s+/g,' ').toUpperCase()));if(invalid.length)throw new Error(`Team Members contains name(s) not assigned to the selected crew: ${invalid.join(', ')}.`);
  }

  persistWorksheet(payload,user,sourceType){
    const settings=this.settings(), now=nowIso(), isUpdate=Boolean(payload.WorksheetID), worksheetId=isUpdate?cleanString(payload.WorksheetID):newId('WS');
    const contractors=this.store.all('Contractors'), crews=this.store.all('Crews'), shifts=this.store.all('Shifts'), workTypes=this.store.all('WorkTypes');
    let contractorId=cleanString(payload.ContractorID); if(String(user.Role)==='Contractor'){if(!user.ContractorID)throw new Error('Your user account is not linked to a contractor.');contractorId=String(user.ContractorID);}
    const contractor=contractors.find(x=>String(x.ContractorID)===contractorId&&truthy(x.Active));if(!contractor)throw new Error('Select a valid active contractor.');
    const crew=crews.find(x=>String(x.CrewID)===String(payload.CrewID)&&truthy(x.Active));if(!crew)throw new Error('Select a valid active crew.');if(String(crew.ContractorID)!==contractorId)throw new Error('The selected crew does not belong to the selected contractor.');
    const shift=shifts.find(x=>String(x.ShiftID)===String(payload.ShiftID)&&truthy(x.Active));if(!shift)throw new Error('Select a valid active shift.');
    const workType=workTypes.find(x=>String(x.WorkTypeID)===String(payload.WorkTypeID)&&truthy(x.Active));if(!workType)throw new Error('Select a valid work type.');
    const dateWorked=normalizeDateString(payload.DateWorked);if(!dateWorked)throw new Error('Date worked is required.');const parish=cleanString(payload.Parish);if(!parish)throw new Error('Parish is required.');this.enforceParish(user,parish);
    const jobsInput=Array.isArray(payload.jobs)?payload.jobs.filter(hasAnyJobData):[];if(!jobsInput.length)throw new Error('Enter at least one job record.');
    const oldWorksheet=isUpdate?this.store.findOne('Worksheets','WorksheetID',worksheetId):null;if(isUpdate&&!oldWorksheet)throw new Error('Worksheet to update was not found.');if(isUpdate&&String(user.Role)==='Contractor'&&String(oldWorksheet.ContractorID)!==contractorId)throw new Error('You cannot edit another contractor’s worksheet.');
    this.validateTeamMembersForCrew(crew.CrewID,payload.TeamMembers,{strict:truthy(payload.StrictTeamMemberValidation)});

    const existingDuplicateKeys=this.existingJobKeysForDate(dateWorked,worksheetId);
    const priorReviewedExceptions=isUpdate&&oldWorksheet&&truthy(payload.PreserveSubmissionIdentity)?this.store.filter('Exceptions','WorksheetID',worksheetId).filter(e=>cleanString(e.JobRecordID)&&cleanString(e.Status).toLowerCase()==='reviewed'):[];
    const priorReviewMap=new Map(priorReviewedExceptions.map(e=>[`${e.JobRecordID}|${e.ExceptionType}`,e]));
    const currentKeys=new Set(), requiredFields=String(settings.REQUIRED_JOB_FIELDS||'').split(',').map(x=>x.trim()).filter(Boolean), jobRecords=[], exceptions=[];
    let timingEligible=0,timingCompliant=0,slaEligible=0,slaCompliant=0,completenessSum=0;
    jobsInput.forEach((input,index)=>{
      const jobId=cleanString(input.JobID), duplicateKey=jobId?`${dateWorked}|${jobId.toUpperCase()}`:'', duplicateSuspected=Boolean(duplicateKey&&(existingDuplicateKeys.has(duplicateKey)||currentKeys.has(duplicateKey)));if(duplicateKey)currentKeys.add(duplicateKey);
      const evaluated=evaluateJob(input,settings,requiredFields), jobRecordId=cleanString(input.JobRecordID)||newId('JOB');completenessSum+=evaluated.completeness;if(evaluated.timingEligible){timingEligible++;if(evaluated.timingValid)timingCompliant++;}if(evaluated.slaEligible){slaEligible++;if(!evaluated.slaException)slaCompliant++;}
      const job={JobRecordID:jobRecordId,WorksheetID:worksheetId,JobSequence:index+1,JobID:jobId,CustomerName:cleanString(input.CustomerName),CustomerAddress:cleanString(input.CustomerAddress),ProblemReported:cleanString(input.ProblemReported),AssignedTime:cleanTime(input.AssignedTime),OnSiteTime:cleanTime(input.OnSiteTime),CompletedTime:cleanTime(input.CompletedTime),AssignToOnSiteMinutes:evaluated.assignToOnSite??'',OnSiteToCompleteMinutes:evaluated.onSiteToComplete??'',AssignToCompleteMinutes:evaluated.assignToComplete??'',ActionTaken:cleanString(input.ActionTaken),MaterialUsed:cleanString(input.MaterialUsed),VoltageFound:cleanString(input.VoltageFound),VoltageLeft:cleanString(input.VoltageLeft),Remarks:cleanString(input.Remarks),RequiredFieldsCompletePercent:round2(evaluated.completeness),DataComplete:evaluated.dataComplete,TimingValid:evaluated.timingValid,TimingException:evaluated.timingException,SLAException:evaluated.slaException,DuplicateSuspected:duplicateSuspected,CreatedAt:cleanString(input.CreatedAt)||now,UpdatedAt:now,ImportBatchID:truthy(input.PreserveImportMetadata)?cleanString(input.ImportBatchID):cleanString(input.ImportBatchID||payload.ImportBatchID),ImportSource:truthy(input.PreserveImportMetadata)?cleanString(input.ImportSource):cleanString(input.ImportSource||payload.ImportSource||sourceType)};jobRecords.push(job);
      for(const ex of evaluated.exceptions)exceptions.push(makeException(worksheetId,jobRecordId,ex.type,ex.severity,ex.description,ex.detected,ex.expected,now));if(duplicateSuspected)exceptions.push(makeException(worksheetId,jobRecordId,'DUPLICATE_JOB_ID','Warning','Potential duplicate Job ID for the same date.',jobId,'Unique Job ID per work date',now));
    });
    const requiredJobs=Math.max(1,num(settings.MIN_JOBS_PER_SHIFT,6)), duplicateJobs=jobRecords.filter(j=>truthy(j.DuplicateSuspected)).length, completedUniqueKeys=new Set();for(const j of jobRecords){if(!j.JobID||!j.CompletedTime)continue;const key=`${dateWorked}|${cleanString(j.JobID).toUpperCase()}`;if(!existingDuplicateKeys.has(key))completedUniqueKeys.add(key);}const jobsCompleted=completedUniqueKeys.size;
    const productionRaw=round2((jobsCompleted/requiredJobs)*100), productionForOverall=Math.min(100,productionRaw), dataCompleteness=jobRecords.length?round2(completenessSum/jobRecords.length):0, timingCompliance=timingEligible?round2(timingCompliant/timingEligible*100):0, slaCompliance=slaEligible?round2(slaCompliant/slaEligible*100):0;
    const weights=normalizeWeights({production:num(settings.OVERALL_WEIGHT_PRODUCTION,50),data:num(settings.OVERALL_WEIGHT_DATA,25),timing:num(settings.OVERALL_WEIGHT_TIMING,15),sla:num(settings.OVERALL_WEIGHT_SLA,10)});const overall=round2(productionForOverall*weights.production+dataCompleteness*weights.data+timingCompliance*weights.timing+slaCompliance*weights.sla),productionStatus=complianceStatus(productionRaw,settings),overallStatus=complianceStatus(overall,settings);
    if(jobsCompleted<requiredJobs){const severity=productionRaw<num(settings.COMPLIANCE_LOW_THRESHOLD,50)?'Critical':'Warning';exceptions.push(makeException(worksheetId,'','LOW_JOB_COUNT',severity,'Unique completed jobs are below the configured minimum for the shift. Suspected duplicates do not increase the production count.',jobsCompleted,requiredJobs,now));}
    if(priorReviewMap.size)for(const ex of exceptions){if(!ex.JobRecordID)continue;const previous=priorReviewMap.get(`${ex.JobRecordID}|${ex.ExceptionType}`);if(previous){ex.Status=previous.Status;ex.ReviewedBy=previous.ReviewedBy;ex.ReviewedAt=previous.ReviewedAt;ex.ResolutionNotes=previous.ResolutionNotes;}}
    const worksheet={WorksheetID:worksheetId,ContractorID:contractorId,ContractorName:contractor.ContractorName,WorkTypeID:workType.WorkTypeID,WorkType:workType.WorkTypeName,DateWorked:dateWorked,Parish:parish,Location:cleanString(payload.Location),CrewID:crew.CrewID,CrewName:crew.CrewName,TeamMembers:cleanString(payload.TeamMembers),ShiftID:shift.ShiftID,ShiftName:shift.ShiftName,SubmittedBy:isUpdate&&oldWorksheet&&truthy(payload.PreserveSubmissionIdentity)?oldWorksheet.SubmittedBy:user.Email,SubmittedByName:isUpdate&&oldWorksheet&&truthy(payload.PreserveSubmissionIdentity)?oldWorksheet.SubmittedByName:(user.Name||displayNameFromEmail(user.Email)),SubmittedAt:isUpdate&&oldWorksheet?oldWorksheet.SubmittedAt:now,JobsCompleted:jobsCompleted,RequiredJobs:requiredJobs,JobVariance:jobsCompleted-requiredJobs,ProductionCompliancePercent:productionRaw,ProductionStatus:productionStatus,DataCompletenessPercent:dataCompleteness,TimingCompliancePercent:timingCompliance,SLACompliancePercent:slaCompliance,OverallCompliancePercent:overall,ComplianceStatus:overallStatus,ExceptionCount:exceptions.length,ReviewStatus:oldWorksheet?.ReviewStatus||'Open',ReviewedBy:oldWorksheet?.ReviewedBy||'',ReviewedAt:oldWorksheet?.ReviewedAt||'',SourceType:isUpdate&&oldWorksheet&&truthy(payload.PreserveSubmissionIdentity)?this.mergeSourceTypes(oldWorksheet.SourceType,sourceType||payload.ImportSource):(sourceType||'Manual Entry'),CreatedAt:oldWorksheet?.CreatedAt||now,UpdatedAt:now};
    this.store.upsert('Worksheets','WorksheetID',worksheet);this.store.deleteWhere('WorksheetJobs','WorksheetID',worksheetId);this.store.insertMany('WorksheetJobs',jobRecords);this.store.deleteWhere('Exceptions','WorksheetID',worksheetId);this.store.insertMany('Exceptions',exceptions);
    this.audit(user,isUpdate?'UPDATE':'CREATE','Worksheet',worksheetId,isUpdate?'Updated worksheet.':'Created worksheet.',oldWorksheet||'',worksheet);
    return{worksheet,jobs:jobRecords,exceptions,summary:{jobsCompleted,duplicateJobs,requiredJobs,jobVariance:jobsCompleted-requiredJobs,productionCompliance:productionRaw,dataCompleteness,timingCompliance,slaCompliance,overallCompliance:overall,status:overallStatus,exceptionCount:exceptions.length}};
  }

  mergeSourceTypes(existing,incoming){return mergeDelimitedValues([existing,incoming],' + ');}
  logicalWorksheetMatches(w,p){return String(w.ContractorID)===String(p.ContractorID)&&normalizeDateString(w.DateWorked)===normalizeDateString(p.DateWorked)&&String(w.CrewID)===String(p.CrewID)&&String(w.ShiftID)===String(p.ShiftID)&&String(w.WorkTypeID)===String(p.WorkTypeID)&&normalizeIdentityText(w.Parish)===normalizeIdentityText(p.Parish);}
  findLogicalWorksheetForImport(payload,user){const matches=this.restrictWorksheets(this.store.all('Worksheets'),user).filter(w=>this.logicalWorksheetMatches(w,payload));if(matches.length>1)throw new Error('Multiple existing worksheets match this contractor/date/crew/shift/work type/parish combination. Resolve the duplicate worksheets before importing additional jobs.');return matches[0]||null;}
  worksheetLockedForImport(w){return['reviewed','finalized','finalised','closed','locked','approved'].includes(cleanString(w?.ReviewStatus).toLowerCase());}
  mapStoredJobForMerge(job){return{JobRecordID:job.JobRecordID,JobID:job.JobID,CustomerName:job.CustomerName,CustomerAddress:job.CustomerAddress,ProblemReported:job.ProblemReported,AssignedTime:job.AssignedTime,OnSiteTime:job.OnSiteTime,CompletedTime:job.CompletedTime,ActionTaken:job.ActionTaken,MaterialUsed:job.MaterialUsed,VoltageFound:job.VoltageFound,VoltageLeft:job.VoltageLeft,Remarks:job.Remarks,CreatedAt:job.CreatedAt,ImportBatchID:job.ImportBatchID,ImportSource:job.ImportSource,PreserveImportMetadata:true};}
  prepareImportPayload(payload,user,sourceType,importBatchId){const existing=this.findLogicalWorksheetForImport(payload,user);const incoming=(payload.jobs||[]).map(j=>({...j,ImportBatchID:importBatchId,ImportSource:sourceType}));if(!existing)return{...payload,jobs:incoming,ImportBatchID:importBatchId,ImportSource:sourceType,PreserveSubmissionIdentity:false,ImportMode:'created',IncomingJobCount:incoming.length,StrictTeamMemberValidation:truthy(payload.StrictTeamMemberValidation)};if(this.worksheetLockedForImport(existing))throw new Error(`A matching worksheet (${existing.WorksheetID}) is already ${cleanString(existing.ReviewStatus||'finalized')} and cannot be changed by bulk import.`);const stored=this.store.filter('WorksheetJobs','WorksheetID',existing.WorksheetID).sort((a,b)=>num(a.JobSequence)-num(b.JobSequence)).map(j=>this.mapStoredJobForMerge(j));return{...payload,WorksheetID:existing.WorksheetID,Location:mergeDelimitedValues([existing.Location,payload.Location],' | '),TeamMembers:mergeDelimitedValues([existing.TeamMembers,payload.TeamMembers],', '),jobs:stored.concat(incoming),ImportBatchID:importBatchId,ImportSource:sourceType,PreserveSubmissionIdentity:true,ImportMode:'merged',ExistingJobCount:stored.length,IncomingJobCount:incoming.length,StrictTeamMemberValidation:truthy(payload.StrictTeamMemberValidation)};}

  validateBulkTemplateMeta(meta,user){const scope={controlled:false,boundContractorId:'',boundContractorName:'',enforceCrewMembers:false};if(!meta||typeof meta!=='object'||!Object.keys(meta).length)return scope;const name=cleanString(meta.TemplateName),version=cleanString(meta.TemplateVersion);if(name&&name!==BULK_TEMPLATE.NAME)throw new Error('The uploaded workbook does not match the controlled Daily Work Sheet bulk import template.');if(version&&version!==BULK_TEMPLATE.VERSION)throw new Error(`Unsupported bulk template version ${version}. Download the current template before importing.`);scope.controlled=Boolean(name||version);scope.boundContractorId=cleanString(meta.GeneratedForContractorID);scope.boundContractorName=cleanString(meta.GeneratedForContractorName);scope.enforceCrewMembers=Boolean(scope.boundContractorId);if(scope.boundContractorId){const c=this.active('Contractors').find(c=>String(c.ContractorID)===scope.boundContractorId);if(!c)throw new Error('The contractor bound to this template is no longer active or could not be found. Download a fresh template.');if(!scope.boundContractorName)scope.boundContractorName=cleanString(c.ContractorName);}if(String(user.Role)==='Contractor'){const own=cleanString(user.ContractorID);if(!own)throw new Error('Your user account is not linked to a contractor.');if(scope.controlled&&!scope.boundContractorId)throw new Error('This controlled template is not bound to a contractor. Download a fresh template while signed in to your contractor account.');if(scope.boundContractorId&&scope.boundContractorId!==own)throw new Error('This controlled template was generated for a different contractor account.');}return scope;}

  normalizeBulkRow(row){const out={};for(const[k,v]of Object.entries(row||{})){const canon=HEADER_ALIASES[normalizeHeader(k)];if(canon)out[canon]=v;}return out;}
  groupBulkRows(rows){const groups={};for(const r of rows){const key=[r.Contractor,normalizeDateString(r.DateWorked),r.Crew,r.Shift,r.WorkType,r.Parish].map(x=>cleanString(x).toUpperCase()).join('|');(groups[key]??=[]).push(r);}return groups;}
  bulkRowsToPayload(rows,user,scope){if(!rows.length)throw new Error('Import group is empty.');const first=rows[0],contractors=this.active('Contractors'),crews=this.active('Crews'),crewMembers=this.active('CrewMembers'),shifts=this.active('Shifts'),workTypes=this.active('WorkTypes'),parishes=this.active('Parishes');const entered=findByIdOrName(contractors,first.Contractor,'ContractorID','ContractorName');let contractor=entered;if(String(user.Role)==='Contractor')contractor=contractors.find(c=>String(c.ContractorID)===String(user.ContractorID));if(!contractor)throw new Error(`Unknown contractor: ${first.Contractor}`);const bound=cleanString(scope?.boundContractorId);if(bound){if(!entered||String(entered.ContractorID)!==bound)throw new Error(`This template is bound to ${cleanString(scope.boundContractorName)||bound}. The Contractor value in the import cannot be changed.`);if(String(contractor.ContractorID)!==bound)throw new Error('The import contractor does not match the contractor bound to this template.');}
    const crew=findByIdOrName(crews.filter(c=>String(c.ContractorID)===String(contractor.ContractorID)),first.Crew,'CrewID','CrewName');if(!crew)throw new Error(`Unknown crew for contractor ${contractor.ContractorName}: ${first.Crew}`);const shift=findByIdOrName(shifts,first.Shift,'ShiftID','ShiftName');if(!shift)throw new Error(`Unknown shift: ${first.Shift}`);const workType=findByIdOrName(workTypes,first.WorkType,'WorkTypeID','WorkTypeName');if(!workType)throw new Error(`Unknown work type: ${first.WorkType}`);const parish=findByIdOrName(parishes,first.Parish,'ParishID','ParishName');if(!parish)throw new Error(`Unknown or inactive parish: ${first.Parish}`);this.enforceParish(user,parish.ParishName);
    const allowedMembers=new Set(crewMembers.filter(m=>String(m.CrewID)===String(crew.CrewID)).map(m=>cleanString(m.EmployeeName).replace(/\s+/g,' ').toUpperCase()).filter(Boolean)), enforce=Boolean(scope?.enforceCrewMembers), dateWorked=validateDate(first.DateWorked);
    const jobs=rows.map((r,index)=>{if(enforce&&cleanString(r.TeamMembers)){const invalid=cleanString(r.TeamMembers).split(/[;,\n]+/).map(cleanString).filter(Boolean).filter(n=>!allowedMembers.has(n.replace(/\s+/g,' ').toUpperCase()));if(invalid.length)throw new Error(`Row ${index+2}: Team Members contains name(s) not assigned to ${crew.CrewName}: ${invalid.join(', ')}.`);}const assigned=normalizeImportedTime(r.AssignedTime),onsite=normalizeImportedTime(r.OnSiteTime),completed=normalizeImportedTime(r.CompletedTime);for(const [raw,val,label] of [[r.AssignedTime,assigned,'Assigned Time'],[r.OnSiteTime,onsite,'On-site Time'],[r.CompletedTime,completed,'Completed Time']])if(cleanString(raw)&&!parseFlexibleTime(val))throw new Error(`Row ${index+2}: ${label} is not a valid time.`);if(assigned&&onsite&&completed){const seq=calculateDurations(assigned,onsite,completed);if(!seq.valid)throw new Error(`Row ${index+2}: ${seq.message}`);}return{JobID:r.JobID,CustomerName:r.CustomerName,CustomerAddress:r.CustomerAddress,ProblemReported:r.ProblemReported,AssignedTime:assigned,OnSiteTime:onsite,CompletedTime:completed,ActionTaken:r.ActionTaken,MaterialUsed:r.MaterialUsed,VoltageFound:r.VoltageFound,VoltageLeft:r.VoltageLeft,Remarks:r.Remarks};});
    return{ContractorID:contractor.ContractorID,WorkTypeID:workType.WorkTypeID,DateWorked:dateWorked,Parish:parish.ParishName,Location:mergeDelimitedValues(rows.map(r=>r.Location),' | '),CrewID:crew.CrewID,TeamMembers:mergeDelimitedValues(rows.map(r=>r.TeamMembers),', '),ShiftID:shift.ShiftID,jobs,StrictTeamMemberValidation:enforce};
  }
  processImportGroups(groups,user,sourceType,importBatchId,scope){const successes=[],errors=[];let created=0,merged=0;for(const [key,rows] of Object.entries(groups)){try{const base=this.bulkRowsToPayload(rows,user,scope),payload=this.prepareImportPayload(base,user,sourceType,importBatchId),mode=payload.ImportMode||'created',incoming=num(payload.IncomingJobCount,base.jobs.length),result=this.persistWorksheet(payload,user,sourceType);if(mode==='merged')merged++;else created++;successes.push({worksheetId:result.worksheet.WorksheetID,date:result.worksheet.DateWorked,crew:result.worksheet.CrewName,mode,jobsAdded:incoming,totalJobs:result.jobs.length,jobsCounted:result.summary.jobsCompleted,duplicates:result.summary.duplicateJobs,status:result.summary.status});}catch(e){errors.push({group:key,message:e.message||String(e),rows:rows.length});}}return{successes,errors,created,merged};}
  importBulkRows(user,rows,templateMeta){this.authorize(user,['Admin','Superuser','Contractor']);const scope=this.validateBulkTemplateMeta(templateMeta,user);if(!Array.isArray(rows)||!rows.length)throw new Error('No import rows were supplied.');if(rows.length>5000)throw new Error('A single import is limited to 5,000 rows. Split larger files into smaller batches.');const normalized=rows.map(r=>this.normalizeBulkRow(r)).filter(r=>Object.values(r).some(v=>cleanString(v)!=='')),groups=this.groupBulkRows(normalized),importBatchId=newId('IMP');return this.store.transaction(()=>{const outcome=this.processImportGroups(groups,user,'Bulk File',importBatchId,scope);this.audit(user,'IMPORT','BulkWorksheet',importBatchId,'Processed bulk import.','',{importBatchId,rows:normalized.length,worksheetGroupsProcessed:outcome.successes.length,worksheetsCreated:outcome.created,worksheetsMerged:outcome.merged,errors:outcome.errors.length});return{imported:outcome.successes.length,created:outcome.created,merged:outcome.merged,failed:outcome.errors.length,importBatchId,successes:outcome.successes,errors:outcome.errors};});}

  async importGoogleSheet(user,source,sheetName,accessToken){this.authorize(user,['Admin','Superuser','Contractor']);if(!accessToken)throw new Error('Google Sheets import requires Google authentication with spreadsheet read permission.');const id=extractSpreadsheetId(source);if(!id)throw new Error('Enter a valid Google Sheets URL or Spreadsheet ID.');const headers={Authorization:`Bearer ${accessToken}`};const metaRes=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}?fields=properties.title,sheets.properties.title`,{headers});if(!metaRes.ok)throw new Error(`Google Sheets metadata request failed (${metaRes.status}).`);const meta=await metaRes.json(), target=sheetName||meta.sheets?.[0]?.properties?.title;if(!target)throw new Error('The source spreadsheet does not contain a sheet.');const valRes=await fetch(`https://sheets.googleapis.com/v4/spreadsheets/${encodeURIComponent(id)}/values/${encodeURIComponent(target)}`,{headers});if(!valRes.ok)throw new Error(`Google Sheets values request failed (${valRes.status}).`);const values=(await valRes.json()).values||[];if(values.length<2)throw new Error('The source sheet does not contain data rows.');const hdr=values[0],rows=values.slice(1).map(row=>Object.fromEntries(hdr.map((h,i)=>[h,row[i]??'']))),normalized=rows.map(r=>this.normalizeBulkRow(r)).filter(r=>Object.values(r).some(v=>cleanString(v)!=='')),groups=this.groupBulkRows(normalized),importBatchId=newId('IMP');return this.store.transaction(()=>{const outcome=this.processImportGroups(groups,user,'Google Sheets Import',importBatchId,null);this.audit(user,'IMPORT','GoogleSheetWorksheet',importBatchId,'Processed Google Sheets import.','',{importBatchId,sourceSpreadsheetId:id,sourceName:meta.properties?.title||'',sheetName:target,rows:normalized.length,worksheetGroupsProcessed:outcome.successes.length,worksheetsCreated:outcome.created,worksheetsMerged:outcome.merged,errors:outcome.errors.length});return{imported:outcome.successes.length,created:outcome.created,merged:outcome.merged,failed:outcome.errors.length,importBatchId,successes:outcome.successes,errors:outcome.errors,sourceName:meta.properties?.title||'',sheetName:target};});}

  getTemplateData(user,targetContractorId){this.authorize(user,['Admin','Superuser','Contractor']);const settings=this.settings(),headers=['Contractor','Work Type','Date Worked','Parish','Location','Crew','Team Members','Shift','Job ID','Customer Name','Customer Address','Problem Reported','Assigned Time','On-site Time','Completed Time','Action Taken','Material Used','Voltage Found','Voltage Left','Remarks'];let parishes=this.active('Parishes'),contractors=this.active('Contractors'),crews=this.active('Crews'),members=this.active('CrewMembers');const role=String(user.Role),requested=cleanString(targetContractorId);let scoped=null;if(role==='Contractor'){if(!user.ContractorID)throw new Error('Your user account is not linked to a contractor.');scoped=contractors.find(x=>String(x.ContractorID)===String(user.ContractorID));if(!scoped)throw new Error('Your linked contractor is not active or could not be found.');}else if(requested){if(role!=='Admin')throw new Error('Only an Admin can generate a template for a selected contractor.');scoped=contractors.find(x=>String(x.ContractorID)===requested);if(!scoped)throw new Error('The selected contractor is not active or could not be found.');}
    const allowed=this.allowedParishes(user);if(allowed.length){const set=new Set(allowed.map(x=>x.toLowerCase()));parishes=parishes.filter(x=>set.has(cleanString(x.ParishName).toLowerCase()));crews=crews.filter(x=>!x.Parish||set.has(cleanString(x.Parish).toLowerCase()));}if(scoped){contractors=contractors.filter(x=>String(x.ContractorID)===String(scoped.ContractorID));crews=crews.filter(x=>String(x.ContractorID)===String(scoped.ContractorID));}const crewIds=new Set(crews.map(x=>String(x.CrewID)));members=members.filter(x=>crewIds.has(String(x.CrewID)));const membersByCrew=new Map(crews.map(x=>[String(x.CrewID),[]]));members.slice().sort((a,b)=>cleanString(a.EmployeeName).localeCompare(cleanString(b.EmployeeName))).forEach(m=>{const n=cleanString(m.EmployeeName);if(n&&membersByCrew.has(String(m.CrewID)))membersByCrew.get(String(m.CrewID)).push(n);});const crewRosterRows=crews.map(c=>[c.CrewName||'',c.CrewID||'',(membersByCrew.get(String(c.CrewID))||[]).join(', ')]),scopeName=scoped?scoped.ContractorName:'';
    const instructions=[['DAILY JOB COMPLETION BULK IMPORT TEMPLATE'],['Use the DataEntry sheet only. One row represents one completed/attempted job. Repeat the worksheet-level fields for each job belonging to the same contractor, date, crew and shift.'],['Worksheet identity is Contractor + Date Worked + Crew + Shift + Work Type + Parish. Later imports matching that identity append jobs to the existing worksheet instead of creating another worksheet.'],['Required worksheet fields: Contractor, Work Type, Date Worked, Parish, Crew, Shift. Required job fields are validated again by the application during import.'],['Date Worked must be a valid date and cannot be later than the date the template is generated. Time fields must contain valid Excel time values; HH:MM (24-hour format) is recommended.'],['Basic chronology is validated in the workbook: Assigned → On-site → Completed. Legitimate overnight transitions are supported.'],['The 15-minute timestamp compliance rule is NOT enforced in this workbook. The application evaluates that rule only after upload and records any resulting compliance exceptions.'],['The minimum jobs-per-shift requirement is not used to block worksheet entry. Submit the actual jobs completed; the application calculates production compliance after import.'],['Contractor, Work Type, Parish, Crew and Shift must be selected from the approved dropdown values supplied with this template.'],['Team Members is automatically populated from the configured active membership of the selected Crew. If an authorized override is entered, the application revalidates the names against that Crew during upload.'],['Workbook structure, headers, reference sheets and instructions are protected. Only intended DataEntry cells are unlocked for entry.'],['Do not rename, remove, reorder or alter the DataEntry headers. CSV imports do not contain workbook protection and are always revalidated by the application.']];if(scoped)instructions.splice(1,0,[`Contractor-bound template: ${scopeName}. Contractor, Crew and Crew Member reference data in this workbook are limited to this contractor.`]);
    return{headers,instructions,parishes:parishes.map(x=>[x.ParishName,x.Region]),contractors:contractors.map(x=>[x.ContractorName,x.ContractorID]),crews:crews.map(x=>[x.CrewName,x.CrewID,x.ContractorID,x.Parish]),crewMembers:crewRosterRows,shifts:this.active('Shifts').map(x=>[x.ShiftName,x.ShiftID,x.StartTime,x.EndTime]),workTypes:this.active('WorkTypes').map(x=>[x.WorkTypeName,x.WorkTypeID]),templateMeta:{TemplateName:BULK_TEMPLATE.NAME,TemplateVersion:BULK_TEMPLATE.VERSION,TemplateID:newId('TPL'),TemplateScope:scoped?'Contractor':'General',GeneratedAt:nowIso(),GeneratedFor:user.Email||'',GeneratedForName:user.Name||'',GeneratedForContractorID:scoped?scoped.ContractorID:'',GeneratedForContractorName:scoped?scoped.ContractorName:'',MinimumJobsPerShift:String(num(settings.MIN_JOBS_PER_SHIFT,6)),HeaderSignature:headers.join('|')}};
  }

  restrictWorksheets(rows,user){let out=rows.slice();if(String(user.Role)==='Contractor')out=out.filter(w=>String(w.ContractorID)===String(user.ContractorID));const allowed=this.allowedParishes(user);if(allowed.length){const set=new Set(allowed.map(x=>x.toLowerCase()));out=out.filter(w=>set.has(cleanString(w.Parish).toLowerCase()));}return out;}
  matchesFilters(w,f={}){if(f.dateFrom&&String(w.DateWorked)<String(f.dateFrom))return false;if(f.dateTo&&String(w.DateWorked)>String(f.dateTo))return false;if(f.month&&!String(w.DateWorked||'').startsWith(String(f.month)))return false;if(f.ContractorID&&String(w.ContractorID)!==String(f.ContractorID))return false;if(f.CrewID&&String(w.CrewID)!==String(f.CrewID))return false;if(f.Parish&&String(w.Parish)!==String(f.Parish))return false;if(f.Status&&String(w.ComplianceStatus)!==String(f.Status))return false;if(f.WorkTypeID&&String(w.WorkTypeID)!==String(f.WorkTypeID))return false;if(f.ShiftID&&String(w.ShiftID)!==String(f.ShiftID))return false;if(f.submittedBy&&normalizeEmail(w.SubmittedBy)!==normalizeEmail(f.submittedBy))return false;return true;}
  aggregatePerformance(worksheets,keyField,labelField){const groups={};for(const w of worksheets){const key=String(w[keyField]||'Unknown');if(!groups[key])groups[key]={Key:key,Name:w[labelField]||key,Worksheets:0,JobsCompleted:0,RequiredJobs:0,JobBalance:0,CompliancePercent:0,AverageOverallCompliance:0,BelowTarget:0,_overall:[]};const g=groups[key];g.Worksheets++;g.JobsCompleted+=num(w.JobsCompleted);g.RequiredJobs+=num(w.RequiredJobs);if(num(w.JobsCompleted)<num(w.RequiredJobs))g.BelowTarget++;g._overall.push(num(w.OverallCompliancePercent));}return Object.values(groups).map(g=>{g.JobBalance=g.JobsCompleted-g.RequiredJobs;g.CompliancePercent=g.RequiredJobs?round2(g.JobsCompleted/g.RequiredJobs*100):0;g.AverageOverallCompliance=averageNumeric(g._overall);delete g._overall;return g;}).sort((a,b)=>b.CompliancePercent-a.CompliancePercent);}
  aggregateTrend(ws){const map={};for(const w of ws){const d=String(w.DateWorked||'Unknown');map[d]??={DateWorked:d,JobsCompleted:0,RequiredJobs:0,Worksheets:0};map[d].JobsCompleted+=num(w.JobsCompleted);map[d].RequiredJobs+=num(w.RequiredJobs);map[d].Worksheets++;}return Object.values(map).map(x=>({...x,CompliancePercent:x.RequiredJobs?round2(x.JobsCompleted/x.RequiredJobs*100):0})).sort((a,b)=>String(a.DateWorked).localeCompare(String(b.DateWorked)));}
  aggregateCount(rows,field){const map={};for(const r of rows){const k=String(r[field]||'Unknown');map[k]=(map[k]||0)+1;}return Object.entries(map).map(([Name,Count])=>({Name,Count})).sort((a,b)=>b.Count-a.Count);}
  buildInsights(metrics,contractorPerf,parishPerf,exceptionBreakdown){if(!metrics.worksheetsSubmitted)return'No worksheet data matches the selected period. Submit worksheets or adjust the filters to generate compliance insights.';const lines=[`Current production compliance is ${metrics.productionCompliance.toFixed(1)}%, with ${metrics.jobsCompleted} completed jobs against a requirement of ${metrics.requiredJobs}.`];lines.push(metrics.teamsBelowTarget>0?`${metrics.teamsBelowTarget} worksheet shift(s) are below the configured minimum job target.`:'All worksheet shifts in the selected period meet or exceed the configured minimum job target.');lines.push(`Average assignment-to-on-site time is ${formatMinutesText(metrics.averageAssignToOnSite)}, while average assignment-to-completion time is ${formatMinutesText(metrics.averageAssignToComplete)}.`);if(metrics.timingExceptions>0)lines.push(`${metrics.timingExceptions} job record(s) have timestamp integrity exceptions.`);if(metrics.incompleteRecords>0)lines.push(`${metrics.incompleteRecords} job record(s) are missing one or more required data points.`);if(contractorPerf.length){const x=contractorPerf.slice().sort((a,b)=>a.CompliancePercent-b.CompliancePercent)[0];if(x?.CompliancePercent<100)lines.push(`${x.Name} has the lowest production compliance at ${x.CompliancePercent.toFixed(1)}% for the selected period.`);}if(parishPerf.length){const x=parishPerf.slice().sort((a,b)=>a.CompliancePercent-b.CompliancePercent)[0];if(x?.CompliancePercent<100)lines.push(`${x.Name} currently shows the lowest parish-level production compliance at ${x.CompliancePercent.toFixed(1)}%.`);}if(exceptionBreakdown.length)lines.push(`The most frequent exception type is ${exceptionBreakdown[0].Name} (${exceptionBreakdown[0].Count}).`);return lines.join(' ');}
  getDashboardData(user,filters){this.authorize(user,['Admin','Superuser','Contractor']);const worksheets=this.restrictWorksheets(this.store.all('Worksheets'),user).filter(w=>this.matchesFilters(w,filters||{})),ids=new Set(worksheets.map(w=>String(w.WorksheetID))),jobs=this.store.all('WorksheetJobs').filter(j=>ids.has(String(j.WorksheetID))),exceptions=this.store.all('Exceptions').filter(e=>ids.has(String(e.WorksheetID))),requiredJobs=sum(worksheets,'RequiredJobs'),jobsCompleted=sum(worksheets,'JobsCompleted'),productionCompliance=requiredJobs?round2(jobsCompleted/requiredJobs*100):0,teamsMeeting=worksheets.filter(w=>num(w.JobsCompleted)>=num(w.RequiredJobs)).length;const metrics={worksheetsSubmitted:worksheets.length,jobsCompleted,requiredJobs,jobBalance:jobsCompleted-requiredJobs,productionCompliance,teamsMeetingTarget:teamsMeeting,teamsBelowTarget:worksheets.length-teamsMeeting,timingExceptions:jobs.filter(j=>truthy(j.TimingException)).length,incompleteRecords:jobs.filter(j=>!truthy(j.DataComplete)).length,openExceptions:exceptions.filter(e=>String(e.Status||'Open')==='Open').length,averageAssignToOnSite:averageNumeric(jobs.map(j=>j.AssignToOnSiteMinutes)),averageOnSiteToComplete:averageNumeric(jobs.map(j=>j.OnSiteToCompleteMinutes)),averageAssignToComplete:averageNumeric(jobs.map(j=>j.AssignToCompleteMinutes)),averageOverallCompliance:averageNumeric(worksheets.map(w=>w.OverallCompliancePercent))};const crewPerformance=this.aggregatePerformance(worksheets,'CrewID','CrewName'),contractorPerformance=this.aggregatePerformance(worksheets,'ContractorID','ContractorName'),parishPerformance=this.aggregatePerformance(worksheets,'Parish','Parish'),dailyTrend=this.aggregateTrend(worksheets),exceptionBreakdown=this.aggregateCount(exceptions,'ExceptionType');return{metrics,crewPerformance,contractorPerformance,parishPerformance,dailyTrend,exceptionBreakdown,insights:this.buildInsights(metrics,contractorPerformance,parishPerformance,exceptionBreakdown)};}
  getReportData(user,filters,reportType){this.authorize(user,['Admin','Superuser','Contractor']);const worksheets=this.restrictWorksheets(this.store.all('Worksheets'),user).filter(w=>this.matchesFilters(w,filters||{})),ids=new Set(worksheets.map(w=>String(w.WorksheetID))),jobs=this.store.all('WorksheetJobs').filter(j=>ids.has(String(j.WorksheetID))),exceptions=this.store.all('Exceptions').filter(e=>ids.has(String(e.WorksheetID))),type=String(reportType||'worksheet').toLowerCase(),wMap=Object.fromEntries(worksheets.map(w=>[String(w.WorksheetID),w]));let rows=[];if(type==='worksheet')rows=worksheets;else if(type==='jobs')rows=jobs.map(j=>({...{DateWorked:wMap[j.WorksheetID]?.DateWorked||'',ContractorName:wMap[j.WorksheetID]?.ContractorName||'',Parish:wMap[j.WorksheetID]?.Parish||'',CrewName:wMap[j.WorksheetID]?.CrewName||'',ShiftName:wMap[j.WorksheetID]?.ShiftName||'',WorkType:wMap[j.WorksheetID]?.WorkType||''},...j}));else if(type==='contractor')rows=this.aggregatePerformance(worksheets,'ContractorID','ContractorName');else if(type==='crew')rows=this.aggregatePerformance(worksheets,'CrewID','CrewName');else if(type==='parish')rows=this.aggregatePerformance(worksheets,'Parish','Parish');else if(type==='timing')rows=jobs.map(j=>({DateWorked:wMap[j.WorksheetID]?.DateWorked||'',ContractorName:wMap[j.WorksheetID]?.ContractorName||'',Parish:wMap[j.WorksheetID]?.Parish||'',CrewName:wMap[j.WorksheetID]?.CrewName||'',JobID:j.JobID,AssignedTime:j.AssignedTime,OnSiteTime:j.OnSiteTime,CompletedTime:j.CompletedTime,AssignToOnSiteMinutes:j.AssignToOnSiteMinutes,OnSiteToCompleteMinutes:j.OnSiteToCompleteMinutes,AssignToCompleteMinutes:j.AssignToCompleteMinutes,TimingException:j.TimingException,SLAException:j.SLAException}));else if(type==='exceptions')rows=exceptions.map(e=>({...{DateWorked:wMap[e.WorksheetID]?.DateWorked||'',ContractorName:wMap[e.WorksheetID]?.ContractorName||'',Parish:wMap[e.WorksheetID]?.Parish||'',CrewName:wMap[e.WorksheetID]?.CrewName||''},...e}));else throw new Error(`Unknown report type: ${reportType}`);return{reportType:type,rows,count:rows.length};}
  getAiInsights(user,filters){const d=this.getDashboardData(user,filters||{});return{insights:d.insights,metrics:d.metrics};}

  getAdminData(user,entity){this.authorize(user,['Admin']);const meta=ADMIN_ENTITIES[entity];if(!meta)throw new Error('Unknown administration entity.');return{entity,keyField:meta.key,headers:SCHEMA[meta.table],rows:this.store.all(meta.table)};}
  saveAdminRecord(user,entity,record){this.authorize(user,['Admin']);const meta=ADMIN_ENTITIES[entity];if(!meta)throw new Error('Unknown administration entity.');const headers=SCHEMA[meta.table],now=nowIso(),obj={};for(const h of headers)obj[h]=record?.[h]!==undefined?sanitizeAdminValue(h,record[h]):'';let key=cleanString(obj[meta.key]);if(!key&&meta.prefix)key=newId(meta.prefix);if(!key)throw new Error(`${meta.key} is required.`);obj[meta.key]=key;if(entity==='Users'){obj.Email=normalizeEmail(obj.Email);if(!obj.Email)throw new Error('Email is required.');if(!['Admin','Superuser','Contractor'].includes(String(obj.Role)))throw new Error('Role must be Admin, Superuser, or Contractor.');if(String(obj.Role)==='Contractor'&&!obj.ContractorID)throw new Error('Contractor users must be linked to a ContractorID.');}if(headers.includes('UpdatedAt'))obj.UpdatedAt=now;const existing=this.store.findOne(meta.table,meta.key,key);if(headers.includes('CreatedAt'))obj.CreatedAt=existing?.CreatedAt||now;this.store.upsert(meta.table,meta.key,obj);this.audit(user,existing?'UPDATE':'CREATE',entity,key,`${existing?'Updated':'Created'} ${entity} record.`,existing||'',obj);return{entity,record:obj,created:!existing};}
  deleteAdminRecord(user,entity,keyValue){this.authorize(user,['Admin']);const meta=ADMIN_ENTITIES[entity];if(!meta)throw new Error('Unknown administration entity.');if(entity==='Settings')throw new Error('Settings records cannot be deleted from the application. Update the value instead.');if(entity==='Users'&&String(keyValue)===String(user.UserID))throw new Error('You cannot delete your own active user record.');const existing=this.store.findOne(meta.table,meta.key,keyValue);if(!existing)throw new Error('Record not found.');this.store.deleteWhere(meta.table,meta.key,keyValue);this.audit(user,'DELETE',entity,keyValue,`Deleted ${entity} record.`,existing,'');return{entity,keyValue};}
  updateExceptionReview(user,exceptionId,status,notes){this.authorize(user,['Admin','Superuser']);const existing=this.store.findOne('Exceptions','ExceptionID',exceptionId);if(!existing)throw new Error('Exception not found.');const updated={...existing,Status:cleanString(status)||'Reviewed',ResolutionNotes:cleanString(notes),ReviewedBy:user.Email,ReviewedAt:nowIso()};this.store.upsert('Exceptions','ExceptionID',updated);this.audit(user,'REVIEW','Exception',exceptionId,'Updated exception review status.',existing,updated);return updated;}
  upgradeLegalContent(user){this.authorize(user,['Admin']);this.store.seedLegal(nowIso(),true);return{updated:this.store.all('LegalContent').map(x=>x.PageKey),legalContentVersion:LEGAL_CONTENT_VERSION,appVersion:APP_VERSION};}
  getApplicationDatabaseInfo(user){this.authorize(user,['Admin']);return{name:'Daily Work Sheet Logging Database',engine:'SQLite',databasePath:this.databasePath,appVersion:APP_VERSION};}
  audit(user,action,entityType,entityId,description,oldValue,newValue){this.store.insert('AuditLog',{AuditID:newId('AUD'),Timestamp:nowIso(),UserEmail:user?.Email||'',UserName:user?.Name||'',Action:action,EntityType:entityType,EntityID:entityId,Description:description,OldValue:stringifySafe(oldValue),NewValue:stringifySafe(newValue)});}
}
